version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: prospector_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prospector
      POSTGRES_USER: prospector
      POSTGRES_PASSWORD: cleo2026
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
