spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prospector?stringtype=unspecified
    username: prospector
    password: cleo2026
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

app:
  overpass:
    endpoint: https://overpass-api.de/api/interpreter
